services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    container_name: grafana
    image: grafana/grafana-enterprise:latest
    restart: unless-stopped
    ports:
      - "3200:3000"
    volumes:
      - 'grafana:/var/lib/grafana'
volumes:
  grafana: {}